# Generated by Django 3.2.4 on 2021-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='projectmanager.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('adviser', 'Adviser')], default='member', max_length=10),
        ),
    ]
