# Generated by Django 3.2.4 on 2021-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20210708_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='projectmanager.Member'),
        ),
    ]
