# Generated by Django 3.2.4 on 2021-07-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20210708_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project'),
        ),
    ]
