# Generated by Django 3.2.4 on 2021-07-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20210708_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='added', to='projectmanager.project'),
        ),
    ]
